from ._criteria import Criteria, CriteriaGroup
from ._criteria import OPERATION_EQUALS, OPERATION_IN, OPERATION_MATCHES, OPERATION_NOT_IN, \
    OPERATION_NOT_OUTLIER, OPERATION_SPECTRUM_NOT_ZERO, OPERATION_NOT_MISSING, \
    OPERATION_GREATER_THAN, OPERATIONS
